<?php

namespace App\Filament\Resources\ParticipanteResource\Pages;

use App\Filament\Resources\ParticipanteResource;
use Filament\Actions;
use Filament\Actions\Action;
use Filament\Resources\Pages\CreateRecord;

class CreateParticipante extends CreateRecord
{
    protected static string $resource = ParticipanteResource::class;

    protected function getCreateAnotherFormAction(): Action
    {
        return parent::getCreateAnotherFormAction()
            ->label('Guardar y crear otro'); // TODO: Change the autogenerated stub
    }

    protected function getCreateFormAction(): Action
    {
        return parent::getCreateFormAction()
            ->label('Guardar'); // TODO: Change the autogenerated stub
    }

    protected function mutateFormDataBeforeCreate(array $data): array
    {
        $id_nivel = auth()->user()->id_nivel;
        $id_entidad = auth()->user()->id_entidad;
        $is_root = auth()->user()->is_root;
        if ($id_nivel != 1 && !$is_root){
             $data['id_entidad'] = $id_entidad;
        }
        return $data;
    }
}
